#Netpyne travis testing script

sudo: false

addons:
  apt:
    packages:
       # Requirements for Neuron/NetPyne/OMV
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 

language: python
python: 2.7

env:
    system_site_packages: true  

install:
    
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
    # Need to pre install NEURON so nrnivmodl can be run targeting mod files in a different directory
    - omv install NEURON
    - pwd
    - python setup.py install
    
    - export NEURON_HOME=/home/travis/neuron/nrn/x86_64/
  

script:
    # - cd doc/source/code/
    # - $NEURON_HOME/bin/nrnivmodl mod
    # - python tut1.py
    - cd examples/HHTut
    - python HHTut_run.py
    

notifications: 
    email: false
    #slack: neurosim:pj4DaRn3CrmH6hSRV0zBhfjS
