#Netpyne travis testing script

sudo: false

addons:
  apt:
    packages:
       # Requirements for Neuron/NetPyne/OMV
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 

language: python
python: 2.7

env:
    system_site_packages: true  

install:
    
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
    # Need to pre install NEURON so nrnivmodl can be run targeting mod files in a different directory
    #- omv install NEURON
    #- python setup.py install
    
    
    

script:


notifications: 
    email: false
    #slack: neurosim:pj4DaRn3CrmH6hSRV0zBhfjS
